model:
  class_path: models.PUNetVariants.LIDCPUNet
  init_args:
    input_channels: 1
    num_classes: 1
    conditioning: image
    aggregate_n_samples: 4
    ignore_index: null
    write_full_val_samples: false
    use_original_scheduler: true
    num_updown_blocks: 4
    lr: 0.0001
    

ckpt_path: null
do_validate: true
do_train: true
do_test: true
seed_everything: 23