class_path: dataloader.CityscapesDataModule.CityscapesDataModule
init_args:
  data_dir: your_path/cityscapes
  quality_mode: fine
  target_type: semantic
  num_workers: 8
  batch_size: 32
  binarization_mode: four