model:
  class_path: models.PUNetVariants.SimfirePUNet
  init_args:
    input_channels: 7
    num_classes: 1
    dataset_evaluator_arg: asymmetric
    conditioning: image
    aggregate_n_samples: 8
    ignore_index: null
    write_full_val_samples: false
    lr: 1e-3
    num_updown_blocks: 4

ckpt_path: null
do_validate: True
do_train: True
do_test: True
seed_everything: 23